DROP TABLE IF EXISTS FILE;

create table if not exists File(
                                   id BIGINT not null PRIMARY KEY,
                                   version varchar(50) not null ,
                                   path varchar(50) not null ,
                                   type varchar(50) not null ,
                                   description varchar(50) not null
);

/*create table if not exists Bee(
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   version varchar(50) not null DEFAULT 'F.001',
                                   path varchar(50) not null DEFAULT '/tmp/test/destination',
                                   type varchar(50) not null DEFAULT 'F300',
                                   description varchar(50) not null DEFAULT 'descr fo 2023'
);*/